### ISSUE TITLE
May I ask for easy keybind change on the config file?

### ISSUE THREAD

**Issue by pompom777** [FeralCompany/FeralMinimap#5]
Is it possible to add keybind change to the config file? so I can change it from in-game with LethalConfig? I wanted to change the keybind and I still have no clue how to do it cause there is no keybind change on the config file

**Comment by FerusGrim** [comment]
@pompom777 Sorry for the late reply, I was away on vacation.

You can change keybinds in-game already using [InputUtils](https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils/). I did not add this functionality to LethalConfig because InputUtils already does a great job at handling in-game keybinds.
